# version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: shopLocal
      POSTGRES_USER: afia
      POSTGRES_PASSWORD: 12345

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true
    environment:
      - VITE_API_URL=http://backend:8000/api
        

volumes:
  postgres_data:
