# Generated by Django 5.1.6 on 2025-03-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_subcategory_product_favoriteproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='offline_store',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='online_store',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
