# Generated by Django 5.1.6 on 2025-03-24 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category_image_alter_favoriteproduct_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_brand',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registration', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, max_length=500, null=True)),
                ('province', models.CharField(max_length=255)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Brand', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
