# Generated by Django 5.1.6 on 2025-04-11 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_brand_id_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='address',
            new_name='store_address',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='offline_store',
            new_name='retail_store',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='brand',
            name='supershop_store',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supershop_store',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='registration',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('name', 'category')},
        ),
        migrations.CreateModel(
            name='SubSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_subcategories', to='store.subcategory')),
            ],
            options={
                'unique_together': {('name', 'subcategory')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sub_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.subsubcategory'),
        ),
    ]
