# Generated by Django 5.1.6 on 2025-04-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_subcategory_alter_product_sub_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='status',
            field=models.CharField(default='Pending'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='Pending'),
        ),
    ]
