# Generated by Django 5.2 on 2025-04-27 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_category_product_tags_userinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='canadian_owned',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='disclaimer_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='manufactured_in',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='origin_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SavedBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'brand')},
            },
        ),
    ]
