# Generated by Django 5.2 on 2025-05-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_brand_canadian_owned_brand_disclaimer_agreed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
